"""initial schema

Revision ID: a7a9d2e99c12
Revises: 
Create Date: 2026-09-12 06:14:52.202205
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'a7a9d2e99c12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor'), 'audit_log', ['actor'], unique=False)
    op.create_index(op.f('ix_audit_log_occurred_at'), 'audit_log', ['occurred_at'], unique=False)
    op.create_table('journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=True),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('position_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('run_mode', sa.String(length=16), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_condition_id'), 'journal', ['condition_id'], unique=False)
    op.create_index(op.f('ix_journal_kind'), 'journal', ['kind'], unique=False)
    op.create_index(op.f('ix_journal_position_id'), 'journal', ['position_id'], unique=False)
    op.create_index(op.f('ix_journal_recorded_at'), 'journal', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_journal_run_mode'), 'journal', ['run_mode'], unique=False)
    op.create_index(op.f('ix_journal_signal_id'), 'journal', ['signal_id'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('token_id', sa.String(length=80), nullable=False),
    sa.Column('best_bid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('best_ask', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('mid', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('spread', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('liquidity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('book_imbalance', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('flow_imbalance', sa.Numeric(precision=12, scale=8), nullable=True),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'captured_at')
    )
    op.create_index(op.f('ix_market_snapshots_captured_at'), 'market_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_market_snapshots_condition_id'), 'market_snapshots', ['condition_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_data_quality'), 'market_snapshots', ['data_quality'], unique=False)
    op.create_index(op.f('ix_market_snapshots_token_id'), 'market_snapshots', ['token_id'], unique=False)
    op.create_index('ix_snapshot_token_time', 'market_snapshots', ['token_id', sa.literal_column('captured_at DESC')], unique=False)
    op.create_table('markets',
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('event_id', sa.String(length=80), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('classification_confidence', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('resolution_validity', sa.String(length=32), nullable=False),
    sa.Column('resolution_criteria', sa.JSON(), nullable=True),
    sa.Column('lifecycle_state', sa.String(length=32), nullable=False),
    sa.Column('outcomes', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_markets_category'), 'markets', ['category'], unique=False)
    op.create_index(op.f('ix_markets_end_date'), 'markets', ['end_date'], unique=False)
    op.create_index(op.f('ix_markets_event_id'), 'markets', ['event_id'], unique=False)
    op.create_index(op.f('ix_markets_lifecycle_state'), 'markets', ['lifecycle_state'], unique=False)
    op.create_index(op.f('ix_markets_resolution_validity'), 'markets', ['resolution_validity'], unique=False)
    op.create_table('positions',
    sa.Column('position_id', sa.String(length=64), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('token_id', sa.String(length=80), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_probability', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('run_mode', sa.String(length=16), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('position_id')
    )
    op.create_index(op.f('ix_positions_closed_at'), 'positions', ['closed_at'], unique=False)
    op.create_index(op.f('ix_positions_condition_id'), 'positions', ['condition_id'], unique=False)
    op.create_index(op.f('ix_positions_opened_at'), 'positions', ['opened_at'], unique=False)
    op.create_index(op.f('ix_positions_run_mode'), 'positions', ['run_mode'], unique=False)
    op.create_index(op.f('ix_positions_token_id'), 'positions', ['token_id'], unique=False)
    op.create_table('reconciliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('discrepancies', sa.JSON(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliations_ran_at'), 'reconciliations', ['ran_at'], unique=False)
    op.create_index(op.f('ix_reconciliations_succeeded'), 'reconciliations', ['succeeded'], unique=False)
    op.create_table('signals',
    sa.Column('signal_id', sa.String(length=64), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('token_id', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('market_probability', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('model_probability', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('edge', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('net_ev', sa.Numeric(precision=12, scale=8), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('smart_money_score', sa.Integer(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_index(op.f('ix_signals_action'), 'signals', ['action'], unique=False)
    op.create_index(op.f('ix_signals_category'), 'signals', ['category'], unique=False)
    op.create_index(op.f('ix_signals_condition_id'), 'signals', ['condition_id'], unique=False)
    op.create_index(op.f('ix_signals_generated_at'), 'signals', ['generated_at'], unique=False)
    op.create_index(op.f('ix_signals_token_id'), 'signals', ['token_id'], unique=False)
    op.create_table('smart_money_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('wallet', sa.String(length=64), nullable=False),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('token_id', sa.String(length=80), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('notional_usdc', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('market_probability_at_entry', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('is_exit', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', 'observed_at')
    )
    op.create_index(op.f('ix_smart_money_events_condition_id'), 'smart_money_events', ['condition_id'], unique=False)
    op.create_index(op.f('ix_smart_money_events_observed_at'), 'smart_money_events', ['observed_at'], unique=False)
    op.create_index(op.f('ix_smart_money_events_wallet'), 'smart_money_events', ['wallet'], unique=False)
    op.create_table('smart_wallets',
    sa.Column('wallet', sa.String(length=64), nullable=False),
    sa.Column('smart_score', sa.Integer(), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('roi', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('accuracy', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('category_specialization', sa.JSON(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('wallet')
    )
    op.create_index(op.f('ix_smart_wallets_smart_score'), 'smart_wallets', ['smart_score'], unique=False)
    op.create_table('orders',
    sa.Column('client_key', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=120), nullable=True),
    sa.Column('signal_id', sa.String(length=64), nullable=True),
    sa.Column('condition_id', sa.String(length=80), nullable=False),
    sa.Column('token_id', sa.String(length=80), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('size_shares', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_shares', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('run_mode', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.signal_id'], ),
    sa.PrimaryKeyConstraint('client_key'),
    sa.UniqueConstraint('client_key', name='uq_orders_client_key')
    )
    op.create_index(op.f('ix_orders_condition_id'), 'orders', ['condition_id'], unique=False)
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_run_mode'), 'orders', ['run_mode'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_token_id'), 'orders', ['token_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_token_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_run_mode'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_condition_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_smart_wallets_smart_score'), table_name='smart_wallets')
    op.drop_table('smart_wallets')
    op.drop_index(op.f('ix_smart_money_events_wallet'), table_name='smart_money_events')
    op.drop_index(op.f('ix_smart_money_events_observed_at'), table_name='smart_money_events')
    op.drop_index(op.f('ix_smart_money_events_condition_id'), table_name='smart_money_events')
    op.drop_table('smart_money_events')
    op.drop_index(op.f('ix_signals_token_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_generated_at'), table_name='signals')
    op.drop_index(op.f('ix_signals_condition_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_category'), table_name='signals')
    op.drop_index(op.f('ix_signals_action'), table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_reconciliations_succeeded'), table_name='reconciliations')
    op.drop_index(op.f('ix_reconciliations_ran_at'), table_name='reconciliations')
    op.drop_table('reconciliations')
    op.drop_index(op.f('ix_positions_token_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_run_mode'), table_name='positions')
    op.drop_index(op.f('ix_positions_opened_at'), table_name='positions')
    op.drop_index(op.f('ix_positions_condition_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_closed_at'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_markets_resolution_validity'), table_name='markets')
    op.drop_index(op.f('ix_markets_lifecycle_state'), table_name='markets')
    op.drop_index(op.f('ix_markets_event_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_end_date'), table_name='markets')
    op.drop_index(op.f('ix_markets_category'), table_name='markets')
    op.drop_table('markets')
    op.drop_index('ix_snapshot_token_time', table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_token_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_data_quality'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_condition_id'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_captured_at'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_journal_signal_id'), table_name='journal')
    op.drop_index(op.f('ix_journal_run_mode'), table_name='journal')
    op.drop_index(op.f('ix_journal_recorded_at'), table_name='journal')
    op.drop_index(op.f('ix_journal_position_id'), table_name='journal')
    op.drop_index(op.f('ix_journal_kind'), table_name='journal')
    op.drop_index(op.f('ix_journal_condition_id'), table_name='journal')
    op.drop_table('journal')
    op.drop_index(op.f('ix_audit_log_occurred_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
